apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-pqcnjiaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-pqcnjiaz 
  name: python-pqcnjiaz
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-pqcnjiaz
    weight: 100 
